"""initial schema: users, forecasting_models, datasets, experiments, results

Revision ID: c56f1b1b8fc0
Revises: 
Create Date: 2026-07-31 18:44:32.022570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c56f1b1b8fc0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecasting_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('family', sa.Enum('classical', 'trained', name='model_family'), nullable=False),
    sa.Column('requires_training', sa.Boolean(), nullable=False),
    sa.Column('default_hyperparams', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('paper_title', sa.Text(), nullable=True),
    sa.Column('publication', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('github_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecasting_models_slug'), 'forecasting_models', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.Enum('system', 'user', name='dataset_source'), nullable=False),
    sa.Column('visibility', sa.Enum('system', 'private', 'public', name='dataset_visibility'), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('frequency', sa.String(length=32), nullable=False),
    sa.Column('period_length', sa.Integer(), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('available_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('selected_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending_column_selection', 'ready', 'error', name='dataset_status'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('experiment_name', sa.String(length=255), nullable=False),
    sa.Column('test_periods', sa.Integer(), nullable=False),
    sa.Column('input_periods', sa.Integer(), nullable=False),
    sa.Column('output_periods', sa.Integer(), nullable=False),
    sa.Column('period_length', sa.Integer(), nullable=False),
    sa.Column('seq_len', sa.Integer(), nullable=False),
    sa.Column('pred_len', sa.Integer(), nullable=False),
    sa.Column('val_ratio', sa.Float(), nullable=False),
    sa.Column('hyperparams', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('has_train_data', sa.Boolean(), nullable=False),
    sa.Column('dataset_snapshot_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='experiment_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['forecasting_models.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('training_time_seconds', sa.Float(), nullable=False),
    sa.Column('num_parameters', sa.Integer(), nullable=True),
    sa.Column('metrics_per_feature', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics_avg', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actual_sequence_path', sa.String(length=1024), nullable=False),
    sa.Column('predicted_sequence_path', sa.String(length=1024), nullable=False),
    sa.Column('plot_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_table('experiments')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_forecasting_models_slug'), table_name='forecasting_models')
    op.drop_table('forecasting_models')
    # ### end Alembic commands ###
